# Initial PC controls; changes made in the settings menu persist here.
[disruptor]
mouse_aim = true
modern_controls = true
vertical_look = false
geometry_correction = true
perspective_textures = true
